"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$scp6r71r6n6^-$e+vx@r$x#(!9)n3)q_)9cb#s87vpoy&9cxh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'index',#Магазин
    'account',#Аккаунты
    'cart',#Корзина
    'orders',#Оформление заказа
    'comments',#Комментарии

    'easy_thumbnails',
    'autoslug',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),'/var/www/static/',)


MEDIA_ROOT          =  "/home/oleg/env-projects/projects/py3env/shop/media"
MEDIA_URL           = '/media/'


LOGIN_URL = 'account:login'
LOGOUT_URL= 'account:logout'
LOGIN_REDIRECT_URL = 'index:home_page'


#Email setting
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'email-email'
EMAIL_HOST_PASSWORD = 'passwordpassword' #Вставь пароль от почты
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'info@radio_fm.ru'
SERVER_EMAIL = 'info@radio_fm.ru'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


#easy_THUMBNAIL

THUMBNAIL_ALIASES = {
    "account.Profile.image": {
        "bw" : {"size": (200,100), "bw":True},
        "small": {"size" : (100,60)},
        "large": {"size" : (200,100)},
        "middle" : {"size": (400,200)},
        "ava" : {"size": (300,300),"crop": ","},
        "comments_ava": {"size": (70, 70)},

    },
    "index.Product_picture.picture_image": {
        "pv": {"size" : (400,400)},
        "chp": {"size" : (122,170)},
            }
}


CART_SESSION_ID = 'cart'